-- MySQL Script generated by MySQL Workbench
-- Thu Feb 28 14:34:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema POST
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema POST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POST` ;
USE `POST` ;

-- -----------------------------------------------------
-- Table `POST`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POST`.`Post` (
  `commentId` INT NOT NULL,
  `questionId` INT NOT NULL,
  `parentCommentId` INT NOT NULL,
  `commentText` VARCHAR(255) NULL,
  `author` INT NOT NULL,
  `dateSubmitted` DATETIME NOT NULL,
  `isEdited` BIT(0) NOT NULL,
  `isDeleted` BIT(0) NOT NULL,
  `numTimesGilded` INT NOT NULL,
  PRIMARY KEY (`commentId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
